services:
  api:
    build: .
    container_name: ${DOCKER_SERVICE_NAME}

    env_file:
      - .env

    ports:
      - ${DOCKER_PORT}:8000

    volumes:
      - ./.:/app/

    networks:
      - backend

networks:
  backend:
    name: ${DOCKER_NETWORK}