from .registry_schema import REGISTRY_VALIDATION_SCHEMA
from .login_schema import LOGIN_VALIDATION_SCHEMA
from .event_schema import EVENT_CREATION_SCHEMA
from .wishlist_schema import WISHLIST_CREATION_SCHEMA