"""Include date columns in event_user for soft delete

Revision ID: 2a87c7790876
Revises: d12092ce34d8
Create Date: 2024-11-11 17:38:43.102405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a87c7790876'
down_revision = 'd12092ce34d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_users', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('event_users', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('event_users', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_users', 'deleted_at')
    op.drop_column('event_users', 'updated_at')
    op.drop_column('event_users', 'created_at')
    # ### end Alembic commands ###
