"""User Event unique constraint

Revision ID: 61ca722637d5
Revises: d9a67e9e5c53
Create Date: 2024-11-10 06:43:59.588361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ca722637d5'
down_revision = 'd9a67e9e5c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_event', 'event_users', ['user_id', 'event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_event', 'event_users', type_='unique')
    # ### end Alembic commands ###
