"""Add Column Drawn to Event

Revision ID: 7cdf9a1a32f5
Revises: 2a87c7790876
Create Date: 2024-11-11 19:28:02.683676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cdf9a1a32f5'
down_revision = '2a87c7790876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('events', sa.Column('drawn', sa.Boolean(), nullable=True))
    op.execute('ALTER TABLE events ADD COLUMN drawn BOOLEAN DEFAULT FALSE AFTER max_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'drawn')
    # ### end Alembic commands ###
