"""Event Unique Constraint

Revision ID: d12092ce34d8
Revises: 61ca722637d5
Create Date: 2024-11-11 05:39:57.155387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12092ce34d8'
down_revision = '61ca722637d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_name_owner', 'events', ['name', 'owner_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_name_owner', 'events', type_='unique')
    # ### end Alembic commands ###
