"""remove column event_id

Revision ID: 90d43ebfdabf
Revises: 7cdf9a1a32f5
Create Date: 2025-05-05 21:05:42.471383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90d43ebfdabf'
down_revision = '7cdf9a1a32f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('wishlist', sa.Column('price', sa.Integer(), nullable=True))
    op.execute('ALTER TABLE wishlist ADD COLUMN price INTEGER AFTER element')
    op.drop_constraint('wishlist_ibfk_1', 'wishlist', type_='foreignkey')
    op.drop_column('wishlist', 'event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('wishlist_ibfk_1', 'wishlist', 'events', ['event_id'], ['id'])
    op.drop_column('wishlist', 'price')
    # ### end Alembic commands ###
